app/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
    path('logos', views.logos_view, name="logos"),
    path('gaming', views.gaming_view, name="gaming"),
]

galappear/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render


def index(request):
    context = {
        "title": "Cari's Site",
        "page_title": "From Index Page"
    }

    return render(request, "app/index.html", context)


def gaming_view(request):
    context = {}
    return render(request, "app/gaming.html", context)


def logos_view(request):
    context = {}
    return render(request, "app/logos.html", context)

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block css %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
         <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/162ff428c2.js" crossorigin="anonymous"></script>
    <title>{{ title }}</title>
</head>
<body>

{% block content %}

{% endblock %}



{% block javascript  %}
        <script
        src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous">

        </script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        <script src="{% static 'js/materialize.js' %}"></script>
        <script>
            $(document).ready(function() {
                // Custom JS & JQuery here

                // Init Sidenav
                $('.sidenav').sidenav();

                // Init modal
                $('.modal').modal()

                // Scrollfire
                const options = [
                    {
                        selector: ".row-1", offset: 50, callback: function(el) {
                            Materialize.fadeInImage($(el))
                        }
                    },
                    {
                        selector: ".row-2", offset: 300, callback: function(el) {
                            Materialize.fadeInImage($(el))
                        }
                    },
                    {
                        selector: ".row-3", offset: 400, callback: function(el) {
                            Materialize.fadeInImage($(el))
                        }
                    }
                ]
                Materialize.scrollFire(options)
            })
        </script>

{% endblock %}

</body>
</html>

app/templates/app/footer.html
{% load static %}
{% block content %}

 <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">About Me</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Site Map</h5>
                  <ul>
                      <li><a class="grey-text text-lighten-5" href="{% url 'app:index' %}">Abstract</a></li>
                      <li><a class="grey-text text-lighten-5" href="{% url 'app:logos' %}">Logos</a></li>
                      <li><a class="grey-text text-lighten-5" href="{% url 'app:gaming' %}">Gaming</a></li>
                      <li><a class="grey-text text-lighten-5" href="#portfolio">Portfolio</a></li>
                      <li><a class="grey-text text-lighten-5" href="#contact">Contact</a></li>
                  </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2020 All rights reserved to Caricia Briones at JDEVS.
            <a class="grey-text text-lighten-4 right" href="#!">Know More</a>
            </div>
          </div>
        </footer>

{% endblock %}

app/templates/app/gaming.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

    {% include 'app/navbar.html' %}

    <section class="section section main">
        <div class="container">
            <!-- Row 1 -->
            <div class="row row-1">
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Clossyp</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/gaming1.jpg' %}" alt="">
                            <span class="card-title">
                                Clossyp
                            </span>
                            <a
                                    href="#gaming1"
                                    class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Row 2 -->
            <div class="row row-2">
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/gaming2.jpg' %}" alt="">
                            <span class="card-title">
                                Voyflen
                            </span>
                            <a
                                    href="#gaming2"
                                    class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                                <i class="material-icons">star_outline</i>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Voyflen</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
            </div>
            <!-- Row 3 -->
            <div class="row row-3">
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Rendann</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/gaming3.jpg' %}" alt="">
                            <span class="card-title">
                                Rendann
                            </span>
                            <a href="#gaming3"
                               class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                                <i class="material-icons">star_outline</i>
                                <i class="material-icons">star_outline</i>
                                <i class="material-icons">star_outline</i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal 1 -->
    <div id="gaming1" class="modal">
        <div class="modal-content">
            <h4>Clossyp</h4>
            <img
                    src="{% static 'images/gallery/gaming1.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
            </p>
        </div>
    </div>
    <!-- Modal 2 -->
    <div id="gaming2" class="modal">
        <div class="modal-content">
            <h4>Voyflen</h4>
            <img
                    src="{% static 'images/gallery/gaming2.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
                <i class="material-icons">star_outline</i>
            </p>
        </div>
    </div>
    <!-- Modal 3 -->
    <div id="gaming3" class="modal">
        <div class="modal-content">
            <h4>Rendann</h4>
            <img
                    src="{% static 'images/gallery/gaming3.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
                <i class="material-icons">star_outline</i>
                <i class="material-icons">star_outline</i>
                <i class="material-icons">star_outline</i>
            </p>
        </div>
    </div>

    {% include 'app/footer.html' %}

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

  {% include 'app/navbar.html' %}
  {% include 'app/main.html' %}
  {% include 'app/footer.html' %}

{% endblock %}

app/templates/app/logos.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

    {% include 'app/navbar.html' %}

    <section class="section section main">
        <div class="container">
            <!-- Row 1 -->
            <div class="row row-1">
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Strizzes</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/logo1.jpg' %}" alt="">
                            <span class="card-title">
                                Strizzes
                            </span>
                            <a
                                    href="#logo1"
                                    class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Row 2 -->
            <div class="row row-2">
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/logo2.jpg' %}" alt="">
                            <span class="card-title">
                                Unix
                            </span>
                            <a
                                    href="#logo2"
                                    class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                                <i class="material-icons">star_outline</i>
                                <i class="material-icons">star_outline</i>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Unix</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
            </div>
            <!-- Row 3 -->
            <div class="row row-3">
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Hosting</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/logo3.jpg' %}" alt="">
                            <span class="card-title">
                                Hosting
                            </span>
                            <a href="#logo3" class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal 1 -->
    <div id="logo1" class="modal">
        <div class="modal-content">
            <h4>Strizzes</h4>
            <img
                    src="{% static 'images/gallery/logo1.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
            </p>
        </div>
    </div>
    <!-- Modal 2 -->
    <div id="logo2" class="modal">
        <div class="modal-content">
            <h4>Unix</h4>
            <img
                    src="{% static 'images/gallery/logo2.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
                <i class="material-icons">star_outline</i>
                <i class="material-icons">star_outline</i>
            </p>
        </div>
    </div>
    <!-- Modal 3 -->
    <div id="logo3" class="modal">
        <div class="modal-content">
            <h4>Hosting</h4>
            <img
                    src="{% static 'images/gallery/logo3.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
            </p>
        </div>
    </div>

    {% include 'app/footer.html' %}

{% endblock %}

app/templates/app/main.html
{% load static %}
{% block content %}

    <section class="section section main">
        <div class="container">
            <!-- Row 1 -->
            <div class="row row-1">
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Diligord</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/abstract1.jpg' %}" alt="">
                            <span class="card-title">
                                Diligord
                            </span>
                            <a
                                    href="#abstract1"
                                    class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Row 2 -->
            <div class="row row-2">
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/abstract2.jpg' %}" alt="">
                            <span class="card-title">
                                Recogged
                            </span>
                            <a
                                    href="#abstract2"
                                    class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                                <i class="material-icons">star_outline</i>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Recogged</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
            </div>
            <!-- Row 3 -->
            <div class="row row-3">
                <div class="col m6 hide-on-small-only">
                    <div class="img-content">
                        <h3>Aleressa</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci alias animi autem
                            consectetur ducimus, nulla quidem ratione recusandae rerum ut.
                        </p>
                    </div>
                </div>
                <div class="col m6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% static 'images/gallery/abstract3.jpg' %}" alt="">
                            <span class="card-title">
                                Aleressa
                            </span>
                            <a href="#abstract3" class="btn-floating halfway-fab waves-effect waves-light red modal-trigger">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="card-content">
                            <p>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star</i>
                                <i class="material-icons">star_half</i>
                                <i class="material-icons">star_outline</i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal 1 -->
    <div id="abstract1" class="modal">
        <div class="modal-content">
            <h4>Diligord</h4>
            <img
                    src="{% static 'images/gallery/abstract1.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
            </p>
        </div>
    </div>
    <!-- Modal 2 -->
    <div id="abstract2" class="modal">
        <div class="modal-content">
            <h4>Recogged</h4>
            <img
                    src="{% static 'images/gallery/abstract2.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
                <i class="material-icons">star_outline</i>
            </p>
        </div>
    </div>
    <!-- Modal 3 -->
    <div id="abstract3" class="modal">
        <div class="modal-content">
            <h4>Aleressa</h4>
            <img
                    src="{% static 'images/gallery/abstract3.jpg' %}"
                    alt=""
                    class="responsive-img">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi consequatur cupiditate ducimus
                error
                excepturi explicabo porro recusandae voluptas voluptates.
            </p>
        </div>
        <div class="modal-footer">
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_half</i>
                <i class="material-icons">star_outline</i>
            </p>
        </div>
    </div>

{% endblock %}

app/templates/app/navbar.html
{% load static %}
{% block content %}

<header class="main-header">
  <nav class="transparent z-depth-0">
    <div class="nav-wrapper">
      <a
        href="#"
        data-target="slide-out"
        data-activates="mobile-demo"
        class="button-collapse show-on-large sidenav-trigger"
      >
        <i class="material-icons">menu</i>
      </a>
      <a href="#home" class="brand-logo">Cari's Site</a>
      <ul class="right hide-on-med-and-down">
        <li class="active"><a href="{% url 'app:index' %}">Abstract</a></li>
        <li><a href="{% url 'app:logos' %}">Logos</a></li>
        <li><a href="{% url 'app:gaming' %}">Gaming</a></li>
        <li><a href="#portfolio">Portfolio</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div>
    <!-- SideNav -->
    <ul id="slide-out" class="sidenav grey darken-4">
      <h4></h4>
        <li><a class="grey-text text-lighten-5" href="{% url 'app:index' %}">Abstract</a></li>
        <li><a class="grey-text text-lighten-5" href="{% url 'app:logos' %}">Logos</a></li>
        <li><a class="grey-text text-lighten-5" href="{% url 'app:gaming' %}">Gaming</a></li>
        <li><a class="grey-text text-lighten-5" href="#portfolio">Portfolio</a></li>
        <li><a class="grey-text text-lighten-5" href="#contact">Contact</a></li>
    </ul>
  </nav>
  <h1 class="center">I build Apps and do <span class="red-text text-accent-3">Graphic Design</span></h1>
  <h4 class="center">Caricia Briones</h4>
</header>

{% endblock %}